// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCEDjKLfetL3Ugsr7uHHkeqW3a5iPQ5W8',
    appId: '1:715637893443:web:e6681d26cabcf30560e7f6',
    messagingSenderId: '715637893443',
    projectId: 'bus-management-7b965',
    authDomain: 'bus-management-7b965.firebaseapp.com',
    storageBucket: 'bus-management-7b965.appspot.com',
    measurementId: 'G-30R4S47176',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChGAMwtlmudVFuSBMgnUQKSKcDGiAbDbE',
    appId: '1:715637893443:android:194c8bc523d59dba60e7f6',
    messagingSenderId: '715637893443',
    projectId: 'bus-management-7b965',
    storageBucket: 'bus-management-7b965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHwnDf1xLCDnENSpGFTz0ONfxu7XlupY4',
    appId: '1:715637893443:ios:138fa34ad4597ef460e7f6',
    messagingSenderId: '715637893443',
    projectId: 'bus-management-7b965',
    storageBucket: 'bus-management-7b965.appspot.com',
    iosClientId: '715637893443-hb5669frj46r8svbqa1tnaoeo1sq1gjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHwnDf1xLCDnENSpGFTz0ONfxu7XlupY4',
    appId: '1:715637893443:ios:138fa34ad4597ef460e7f6',
    messagingSenderId: '715637893443',
    projectId: 'bus-management-7b965',
    storageBucket: 'bus-management-7b965.appspot.com',
    iosClientId: '715637893443-hb5669frj46r8svbqa1tnaoeo1sq1gjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCEDjKLfetL3Ugsr7uHHkeqW3a5iPQ5W8',
    appId: '1:715637893443:web:b981c46fa7d825c860e7f6',
    messagingSenderId: '715637893443',
    projectId: 'bus-management-7b965',
    authDomain: 'bus-management-7b965.firebaseapp.com',
    storageBucket: 'bus-management-7b965.appspot.com',
    measurementId: 'G-HNYQSZYQXX',
  );
}
